version: '3'

services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/sites/:/etc/nginx/sites-available
      - ./logs:/var/log
    ports:
      - "3333:80"


