version: '3'

services:
  database:
    build:
      context: ../docker/database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql
      - ../dump:/home/dump
  redis:
    hostname: redis
    build:
      context: ../docker/redis
      args:
        - REDIS_VER=5
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/data/redis:/data:rw
      - ./logs/redis:/var/log/:rw
    restart: always
  php-fpm:
    build:
      context: ./php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?serverVersion=5.7
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - ../app:/var/www
#      - ./php.ini:/usr/local/etc/php/custom.d
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../app:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "${APP_PORT}:80"
      - "443:443"


