version: '3'

services:
  database:
    build:
      context: ../docker-central/database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql
      - ../dump:/home/dump
  redis:
    hostname: redis
    build:
      context: ./redis
      args:
        - REDIS_VER=5
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/data/redis:/data:rw
      - ./logs/redis:/var/log/:rw
    restart: always
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/sites/:/etc/nginx/sites-available
      - ./logs:/var/log
    ports:
      - "3333:80"


