easy_admin:
    site_name: KTKT ЧНТУ
    design:
      templates:
        layout: 'admin/layout.html.twig' # templates/layout.html.twig
      menu:
        - label: 'Контент'
          icon: 'newspaper-o'
          children:
            - { entity: 'Article', label: 'Статті' }
            - { entity: 'CategoryArticle', label: 'Категорі' }
            - { entity: 'Advertisement', label: 'Оголошення' }
            - { entity: 'Comment', label: 'Коментарі' }
            - { entity: 'user', label: 'Пользователи' }
            - { entity: 'Page', label: 'Сторінки' }
        - label: 'Меню'
          icon: 'newspaper-o'
          children:
            - { entity: 'Menu', label: 'Внутрішнє меню' }
            - { entity: 'Button', label: 'Блоки меню' }
            - { entity: 'MainMenu', label: 'Головне меню' }


    entities:
        Article:
          class: App\Entity\Article
          list:
            fields:
              - { property: 'title' }
              - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
              - { property: 'description' }
#              - { property: 'text' }
              - { property: 'categories' }
            show:
              fields:
                - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
          form:
            fields:
              - { property: 'title' }
              - { property: 'description' }
              - { property: 'imageFile', type: 'vich_image' }
              - { property: 'body' ,type: 'fos_ckeditor'}
              - { property: 'categories' }
        Menu:
          class: App\Entity\Menu
          list:
            fields:
              - { property: 'title' }
              - { property: 'url' }
              - { property: 'page' }
              - { property: 'parent'}
            show:
              fields:
                - { property: 'title' }
                - { property: 'url' }
                - { property: 'page' }
                - { property: 'parent'}
          form:
            fields:
              - { property: 'title' }
              - { property: 'url' }
              - { property: 'page' }
              - { property: 'parent'}
        Button:
          class: App\Entity\Button
        MainMenu:
          class: App\Entity\MainMenu
        Page:
          class: App\Entity\Page
          list:
            fields:
              - { property: 'title' }
              - { property: 'AlisEn' }
              - { property: 'body' ,type: 'fos_ckeditor'}
            show:
              fields:
                - { property: 'title' }
                - { property: 'AlisEn' }
                - { property: 'body' ,type: 'fos_ckeditor'}
          form:
            fields:
              - { property: 'title' }
              - { property: 'body' ,type: 'fos_ckeditor'}
        CategoryArticle:
            class: App\Entity\CategoryArticle
        Advertisement:
          class: App\Entity\Advertisement
          list:
            fields:
              - { property: 'title' }
              - { property: 'description' }
          show:
            fields:
              - { property: 'title' }
              - { property: 'description' }
          form:
            fields:
              - { property: 'title', type: 'fos_ckeditor'}
              - { property: 'description',type: 'text'  }
        Comment:
          class: App\Entity\Comment
        user:
          class: App\Entity\User
          form:
            fields:
              - username
              - email
              - enabled
              - lastLogin
              # if administrators are allowed to edit users' passwords and roles, add this:
              - { property: 'plainPassword', type: 'text', type_options: { required: false } }
              - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
        JournalGroup:
          class: App\Entity\JournalGroup
        JournalTeacher:
          class: App\Entity\JournalTeacher
        JournalSpecialty:
          class: App\Entity\JournalSpecialty
        JournalStudent:
          class: App\Entity\JournalStudent
        JournalSubject:
          class: App\Entity\JournalSubject




      # - App\Entity\Comment
       #- App\Entity\Advertisement
       #- App\Entity\CategoryArticle
