# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    styles:
        my_styles: []
    default_config: default
    configs:
        default:
            language: en
            bodyClass: 'guide'
            filebrowserBrowseRoute: elfinder
            format_tags: 'p;h2;h3;div'
            stylesSet: my_styles
            filebrowserBrowseRouteParameters: []
            removePlugins: 'styles'
            allowedContent: true
            toolbar:
                - [Bold, Italic, Underline, TextColor, -, Cut, Copy, Paste,
                   PasteText, PasteFromWord, -, Undo, Redo, -,
                   BulletedList,NumberedList, -, Outdent, Indent, -]
                - [JustifyLeft, JustifyCenter, JustifyRight]
                - [Blockquote, -, Image, Link, Unlink, Table]
                - [Format, Styles,Maximize, Templates, Source]
