vich_uploader:
    db_driver: orm

    mappings:
       article:
           uri_prefix:         '%app.path.article_images%'
           upload_destination: '%kernel.project_dir%/public/images/article'
